name: ecommer_skincare_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: 
  firebase: 
  firebase_auth:
  firebase_core: 
  firebase_storage: 
  flutter:
    sdk: flutter
  get: ^4.6.6
  iconsax: ^0.0.8
  image_picker: ^1.0.7
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/