// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbIq_Y5HpAryBlBLy9ThOHiFQhVJFuJlw',
    appId: '1:71616844051:web:3088ca3090de5d7da94ae6',
    messagingSenderId: '71616844051',
    projectId: 'e-commerce-24772',
    authDomain: 'e-commerce-24772.firebaseapp.com',
    storageBucket: 'e-commerce-24772.firebasestorage.app',
    measurementId: 'G-Q5Y6QWTN3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcDKyfyKO-dly9KKMHR9F71OrteOwO09c',
    appId: '1:71616844051:android:a167807397b4660da94ae6',
    messagingSenderId: '71616844051',
    projectId: 'e-commerce-24772',
    storageBucket: 'e-commerce-24772.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY-JO2IYJNDbXH1IBw6pT9Zds_jplk9HA',
    appId: '1:71616844051:ios:55969b8afb35d92ea94ae6',
    messagingSenderId: '71616844051',
    projectId: 'e-commerce-24772',
    storageBucket: 'e-commerce-24772.firebasestorage.app',
    iosBundleId: 'com.example.ecommerSkincareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY-JO2IYJNDbXH1IBw6pT9Zds_jplk9HA',
    appId: '1:71616844051:ios:55969b8afb35d92ea94ae6',
    messagingSenderId: '71616844051',
    projectId: 'e-commerce-24772',
    storageBucket: 'e-commerce-24772.firebasestorage.app',
    iosBundleId: 'com.example.ecommerSkincareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbIq_Y5HpAryBlBLy9ThOHiFQhVJFuJlw',
    appId: '1:71616844051:web:f47fadeffce17430a94ae6',
    messagingSenderId: '71616844051',
    projectId: 'e-commerce-24772',
    authDomain: 'e-commerce-24772.firebaseapp.com',
    storageBucket: 'e-commerce-24772.firebasestorage.app',
    measurementId: 'G-KJ5H47KYCC',
  );
}
